---
title: "Introduction to tmbExtract"
author: "Jemay Salomon"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
lang: "fr"
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: TRUE
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: TRUE
colorlinks: true
urlcolor: blue
abstract: "This document aims at introducing the package tmbExtract and show to extract parameters from TMB output."
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


<div align="justify">

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(knitr))
opts_chunk$set(echo=TRUE, warning=TRUE, message=TRUE, cache=FALSE,
               fig.align="center")
opts_knit$set(progress=TRUE, verbose=TRUE)
```


# Preamble

Paths:

Dependencies:
```{r}
suppressPackageStartupMessages(library(TMB))
suppressPackageStartupMessages(library(tmbExtract))
```

Execution time (see the appendix):
```{r time_0}
t0 <- proc.time()
```


# Data
```{r}

```

# TMB model
```{r}

```

# Construct MakeADFun object and fit model
```{r}

```

# Extract parameters and compare with simulated data 
```{r}

```


# Appendix

```{r info}
t1 <- proc.time(); t1 - t0
print(sessionInfo(), locale=FALSE)
```

